libvirt: virsh_edit: Add maximum option for vcpucount
* In RHEL-6, vcpucount --config option must be used with --maximum
  or --active option, using only --config option with cause error:

  > virsh vcpucount virt-tests-vm1 --config
  error: when using --config, either --maximum or --active must
  be specified

* The vm need to backup with '--inactive' option to avoid xml
  inconsistence.

* No need to disable pylint E1111

* Fix some pylint/pep8 problem.

Signed-off-by: Liu Hao <liuhaonk@gmail.com>