libivrt: Fix virsh_domjobabort race condition
Sometimes the virsh_domjobabort test failed with:

error: Requested operation is not valid: no job is active on the domain

because the job finished earlier than the 'domjobabort' command was
issued.  This patch makes all the relevant jobs go out to a named pipe
which doesn't read the whole domain in order to stop the job until the
abort request.

Signed-off-by: Martin Kletzander <mkletzan@redhat.com>