libvirt_xml.vm_xml: fix typo that leads to attribute error
The commit e310f272f9 introduces this problem.
The error message as following,
  AttributeError: 'VMCPUXML' object has no attribute 'mashal_to_cell'