virttest.utils_net: check whether ovs is none before using it
Now when using find_current_bridge, if the host not install openvswitch
it will raise like:
AttributeError: 'NoneType' object has no attribute 'port_to_br'

This patch add a check whether ovs is exist before using it.

Signed-off-by: Yunping Zheng <yunzheng@redhat.com>