virsh_dumpxml: Need to populate output
Commit id '7bdea150' removed the setting of output in the try/except
to call virsh.dumpxml, resulting in the error:

UnboundLocalError: local variable 'output' referenced before assignment.

This change just sets output from the cmd_result