virttest/utils_libguestfs: fix bug for guestfish
The c51a2b2 introduces a bug,
which leads program would never enter 'else' block.
So, even if we specify option '-i',
it still report the following error message,
  libguestfs:
  error: umount_all: call launch before using this function
  (in guestfish, don't forget to use the 'run' command)