qemu: Refactor netperf_udp test script
Add error.context.
Fix bug that get_remote_host_session get an None hostname/IP
Update default adjacent throughput to 0.3
Fix bug that AttributeError: 'module' object has no attribute 'remote_login'


Changes from v1:
Correct import link.
Changes from v2:
Kill netserver by killall -9
Changes from v3:
Typo fix.
Delete code used to close session. As framework will handle it.
Changes from v4:
Delete meaningless logging.debug according to xu's comments.
Changes from v5:
Code style update.
Update the way to get netperf path, make it works for new tree.

Signed-off-by: Feng Yang <fyang@redhat.com>
Acked-by:  Xu Tian <xutian@redhat.com>