utils_misc: always update parameters in subclass_pre_init()
upstream commit id:
fa524acaf9bca0399ef92431105be04b9a9b53a0
Author: Amos Kong <akong@redhat.com>
Date:   Fri Aug 31 15:37:15 2012 +0800

    utils_misc: always update parameters in subclass_pre_init()

    I tried to execute boot and netperf tests in one job,
    but netperf which needs two nics failed and got this
    error: "IndexError: list index out of range"

    After executed boot subtest, vm class was restored into env file,
    in the second test, cloned VMNet class has attributes (vm_name,
    params, container_class), so the parameters could not be updated.

    This patch makes parameters can be updated all the time.

    Signed-off-by: Amos Kong <akong@redhat.com>


Signed-off-by: Feng Yang <fyang@redhat.com>
Acked-by: Yiqiao Pu <ypu@redhat.com>