run: Fix crash when $AUTOTEST_PATH is not set
Fix issue introduced by commit 6ddc6783f9cd73b4deba94cb45df5b8ff16acc1c:

  $ ./run -h
  Traceback (most recent call last):
    File "./run", line 976, in <module>
      app = VirtTestApp()
    File "./run", line 483, in __init__
      self.system_setup()
    File "./run", line 468, in system_setup
      _import_autotest_modules()
    File "./run", line 102, in _import_autotest_modules
      autotest_dir = os.path.expanduser(os.environ.get('AUTOTEST_PATH'))
    File "/usr/lib64/python2.7/posixpath.py", line 261, in expanduser
      if not path.startswith('~'):
  AttributeError: 'NoneType' object has no attribute 'startswith'

Signed-off-by: Eduardo Habkost <ehabkost@redhat.com>