virt: Adapt the utils_misc_unittest to new utils_misc.
Commit f9ec296d (Update utils to support pin multiple threads to one node)
changed the utils_misc.NumaNode, then the unittest of it got a fail:

	# python virttest/utils_misc_unittest.py
	.F.F......WARNING:root:Git repo foo tag is not signed
	WARNING:root:This means we will not verify if the key was made by whomever claims to have made it (dangerous)
	...
	======================================================================
	FAIL: test_free_cpu (__main__.TestNumaNode)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "virttest/utils_misc_unittest.py", line 177, in test_free_cpu
	    self.assertEqual(self.numa_node.dict["0"], "1230")
	AssertionError: ['1230'] != '1230'

	======================================================================
	FAIL: test_pin_cpu (__main__.TestNumaNode)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "virttest/utils_misc_unittest.py", line 150, in test_pin_cpu
	    self.assertEqual(self.numa_node.dict["0"], "1230")
	AssertionError: ['1230'] != '1230'

	----------------------------------------------------------------------
	Ran 13 tests in 0.003s

	FAILED (failures=2)

This patch adapt the unittest to the new data type.

	# python virttest/utils_misc_unittest.py
	..........WARNING:root:Git repo foo tag is not signed
	WARNING:root:This means we will not verify if the key was made by whomever claims to have made it (dangerous)
	...
	----------------------------------------------------------------------
	Ran 13 tests in 0.002s

	OK

Signed-off-by: Dongsheng Yang <yangds.fnst@cn.fujitsu.com>