KVM Test: Check tapfd available before delete it in nic
Already fix this in upstream:
commit 13ef8678ca50d0459c011aad683e220fab6f4fad
Author: Feng Yang <fyang@redhat.com>
Date:   Fri Dec 28 12:54:57 2012 +0000

    virttest: Check tapfd available before delete it in nic.

    Currently we check tapfd_id vaailable before close nic.tapfd.
    When testing with sr-iov device, tapfd_id available not means
    nic.tapfd available. We may get error here.
      File "/root/autotest-devel/client/virt/kvm_vm.py", line 1897, in create
        os.close(int(nic.tapfd))
      File "/root/autotest-devel/client/virt/utils_misc.py", line 386, in __getattribute__
        raise PropCanValueError(propertea, self.__slots__)
    PropCanValueError: Instance contains None value for valid key 'tapfd'

    Signed-off-by: Feng Yang <fyang@redhat.com>


Signed-off-by: Feng Yang <fyang@redhat.com>
Acked-by: Xiaoqing Wei <xwei@redhat.com>