virttest.funcatexit: Prevent weird errors while storing nasty args
Because all arguments are stored in env we have to ensure the arguments
are pickable before storing them. Otherwise users would get weird errors
pointing at env:
    TypeError: can't pickle ... objects

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>