Fix libvirtd status check function
If libvirtd not running(stop, corrdump, etc.), service check command
always exit with code 3:
$ service libvirtd status
Redirecting to /bin/systemctl status  libvirtd.service
libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; disabled)
   Active: inactive (dead) since Tue 2014-03-18 17:43:26 CST; 3h 9min ago
  Process: 6034 ExecStart=/usr/sbin/libvirtd $LIBVIRTD_ARGS (code=exited, status=0/SUCCESS)
 Main PID: 6034 (code=exited, status=0/SUCCESS)

$ echo $?
3

And it's wrong to raise LibvirtdActionError, on system which using
systemd, it may looks like:
LibvirtdActionError: Failed to status libvirtd.
Detail: Redirecting to /bin/systemctl status  libvirtd.service

So remove this exception and just output the debug log.

Signed-off-by: Yanbing Du <ydu@redhat.com>